config/routes.rb
Rails.application.routes.draw do
  get 'categories', to: "categories#index"
  get 'categories/show'
  get 'products', to: "products#index"
  get 'products/show'
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'search', to: 'pages#search'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, :categories, :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception

  def to_s
    category_name
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products, dependent: :restrict_with_exception
  has_many :products, through: :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_products, dependent: :restrict_with_exception
  has_many :product_images

  validates :product_name, :product_price, :stock_quantity, presence: true

  def to_s
    product_name
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  validates :image_title, presence: true
  has_one_attached :image
end

app/models/province.rb
class Province < ApplicationRecord
  has_one :customer, dependent: :restrict_with_exception
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_cart

  def add_to_cart
    id = params[:id].to_i
    cart_event = params[:cart_event]

    if cart_event == "+"
      session[:cart].each do |product|
        product.cart_quantity += 1 if product.id == id
      end
    end
    session[:cart] << id unless session[:cart].include?(id)
    redirect_back(fallback_location: root_path) # returns user back to where they were
  end

  def remove_from_cart
    id = params[:id].to_i
    cart_event = params[:cart_event]

    if cart_event.equal?("-")
      session[:cart].each do |product|
        product.cart_quantity -= 1 if product.id.equal?(id)
        session[:cart].delete(id) if product.cart_quantity.zero?
      end
    else
      session[:cart].delete(id)
    end

    redirect_back(fallback_location: root_path) # returns user back to where they were
  end

  private

  def initialize_session
    session[:visit_count] ||= 0 # Initialize visit count
    session[:cart] ||= []
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: params[:id]).page(params[:page]).per(15)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def search
    if params[:category] == "all"
      @products = Product.where("product_name LIKE ?", "%#{params[:product]}%").page(params[:page]).per(15)
    else
      @category = Category.find(params[:category])
      @products = Product.where("product_name LIKE ? AND category_id = ?", "%#{params[:product]}%",
                                params[:category]).page(params[:page]).per(15)
    end
  end

  def contact
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :initialize_session
  before_action :increment_visit_count, only: [:show]

  def index
    @products = Product.includes(:product_images, :category)
                       .all.page(params[:page]).per(15).order(:product_name)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def initialize_session
    session[:visit_count] ||= 0 # Initialize visit count
  end

  def increment_visit_count
    session[:visit_count] += 1 # Increment the count
    @visit_count = session[:visit_count]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<nav aria-label="breadcrumb no-bg">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Categories</li>
  </ol>
</nav>
<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <% @categories.each do |category| %>
      <div class="list-group">
        <%= link_to category, category, :class => "list-group-item list-group-item-action list-group-item-light" %>
      </div>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<nav aria-label="breadcrumb no-bg">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/categories">Categories</a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @category %></li>
  </ol>
</nav>
<%= render partial: "products/products" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdventuresTimeApparel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "pages/navigation" %>
<!--    <h5>You visited a product <%#= pluralize @visit_count, 'time' %></h5>-->
    <%= yield %>
    <%#= render partial: "pages/footer" %>
  </body>
</html>

app/views/pages/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Adventure Time Apparel</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-cart-plus mr-2"></i>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        <% if @cart.empty? %>
          <p class="dropdown-item"> No Items In Cart </p>
        <% else %>
          <% @cart.each do |product| %>
            <p class="dropdown-item" type="button"><%= product.product_name %>
              <%= link_to 'Remove From Cart', remove_from_cart_path(product.id),
                            method: :delete,
                            class: 'btn btn-outline-warning px-3' %>
              <%= link_to '+', add_to_cart_path(product.id, cart_action:"+"),
                          method: :post,
                          class: 'btn btn-outline-warning px-3' %>
              <%= link_to '-', remove_from_cart_path(product.id, cart_action:"-"),
                          method: :delete,
                          class: 'btn btn-outline-warning px-3' %>

            </p>
          <% end %>
        <% end %>
      </div>
    </div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/products">Products</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Category.all.order('category_name ASC').each do |category| %>
            <%= link_to category, category, :class => "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact Us</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-md-0" action="/search" method="GET">
      <div class = "input-group">
        <input class="form-control" type="search" placeholder="Search By Category" aria-label="Search" name="product">
        <label>
          <select class="custom-select" name = "category">
            <option selected value = "all">Choose Category</option>
            <% Category.all.order('category_name ASC').each do |category| %>
            <option value="<%= category.id %>"><%= link_to category, category, :class => "dropdown-item" %></option>
            <% end %>
          </select>
        </label>
        <div  class = "input-group-append">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Submit">Search</button>
        </div>
      </div>
    </form>
  </div>
</nav>

app/views/pages/about.html.erb
<div class="jumbotron">
  <div class="container">
    <%= link_to 'Home', root_path %>
    <h1 id="adventure-time-apparel">Adventure Time Apparel</h1>
    <h2 id="ecommerce-site-built-with-rails">Ecommerce site built with Rails</h2>
    <ul>
      <li>Built with Ruby v 2.7.1 </li>
    </ul>
    <h3 id="describe-datasets">Datasets</h3>
    <ul>
      <li>Customer – responsible for holding information and account of customer making the purchase of apparel, this will allow order fulfillment<ul>
        <li>Associations <ul>
          <li>has_many (Orders)</li>
          <li>has_one (Province)</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>Customer_name – string</li>
          <li>Email – string</li>
          <li>Password – string</li>
          <li>Address – string</li>
          <li>City – string</li>
          <li>Province – string</li>
          <li>Postal_code – string</li>
          <li>Country – string</li>
        </ul>
        </li>
      </ul>
      </li>
      <li>Province – contains taxes information for the province that will later be used during order GST and PST calculation<ul>
        <li>Associations<ul>
          <li>has_one (Customer)</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>province_name – string</li>
          <li>GST_rate – string</li>
          <li>PST_rate – string</li>
        </ul>
        </li>
      </ul>
      </li>
      <li>Order – Holds information about a specific order a customer has made as well as the order cost<ul>
        <li>Associations<ul>
          <li>Belongs_to (Customer)</li>
          <li>Has_many (Products) through OrderProduct</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>Shipping_address – string</li>
          <li>Order_cost – float</li>
          <li>Shipping_cost – float</li>
          <li>GST – float</li>
          <li>PST – float</li>
        </ul>
        </li>
      </ul>
      </li>
      <li>OrderProduct – a join table allowing for order to have multiple products.<ul>
        <li>Associations<ul>
          <li>Belongs_to (Product)</li>
          <li>Belongs_to (Order)</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>Product_quantity – integer</li>
          <li>Quantity_price  float</li>
        </ul>
        </li>
      </ul>
      </li>
      <li>Product – table containing all information about a product.<ul>
        <li>Associations<ul>
          <li>Belongs_to (Category)</li>
          <li>Has_many (ProductImage)</li>
          <li>Has_many (OrderProducts)</li>
          <li>Has_many (Orders) through OrderProduct</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>Product_name – string</li>
          <li>product_price – float</li>
          <li>stock_quantity – integer</li>
        </ul>
        </li>
      </ul>
      </li>
      <li>Category – table containing all the existing categories of products<ul>
        <li>Associations<ul>
          <li>Has_many (Product)</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>Category_name – string</li>
        </ul>
        </li>
      </ul>
      </li>
      <li>ProductImage – table containing images for products<ul>
        <li>Associations<ul>
          <li>Belongs_to (Product)</li>
        </ul>
        </li>
        <li>Column names<ul>
          <li>Image_title – string</li>
          <li>Image_url – string</li>
        </ul>
        </li>
      </ul>
      </li>
    </ul>
    <h3 id="1-2-erd-diagram">ERD Diagram</h3>
    <p><%= image_tag "FinalProposalERD.png", :class => "img-fluid",:alt => 'ERD'%></p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
  <div class="container">
<!--Section: Contact v.2-->
<section class="mb-4">

  <!--Section heading-->
  <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
  <!--Section description-->
  <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please feel free to contact us</p>

  <div class="row">

    <!--Grid column-->
    <div class="col-md-9 mb-md-0 mb-5">
<!--      <form id="contact-form" name="contact-form" action="/" method="POST">-->
        <form id="contact-form" name="contact-form">
        <!--Grid row-->
        <div class="row">

          <!--Grid column-->
          <div class="col-md-6">
            <div class="md-form mb-0">
              <input type="text" id="name" name="name" class="form-control">
              <label for="name" class="">Your name</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6">
            <div class="md-form mb-0">
              <input type="text" id="email" name="email" class="form-control">
              <label for="email" class="">Your email</label>
            </div>
          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">
          <div class="col-md-12">
            <div class="md-form mb-0">
              <input type="text" id="subject" name="subject" class="form-control">
              <label for="subject" class="">Subject</label>
            </div>
          </div>
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">

          <!--Grid column-->
          <div class="col-md-12">

            <div class="md-form">
              <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
              <label for="message">Your message</label>
            </div>

          </div>
        </div>
        <!--Grid row-->

      </form>

      <div class="text-center text-md-left">
        <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
      </div>
      <div class="status"></div>
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-3 text-center">
      <ul class="list-unstyled mb-0">
        <li><i class="fas fa-map-marker-alt fa-2x"></i>
          <p>Winnipeg, MB, CA</p>
        </li>

        <li><i class="fas fa-phone mt-4 fa-2x"></i>
          <p>1(204)222-2222</p>
        </li>

        <li><i class="fas fa-envelope mt-4 fa-2x"></i>
          <p>contact@ata.com</p>
        </li>
      </ul>
    </div>
    <!--Grid column-->

  </div>

</section>
<!--Section: Contact v.2-->
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Adventure Time Apparel</h1>
    <p class="lead">This is an ecommerce website specializing in Adventure and Camping Apparel </p>
  </div>
</div>

app/views/pages/search.html.erb
<nav aria-label="breadcrumb no-bg">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/categories">Categories</a></li>
    <li class="breadcrumb-item"><%= link_to @category, @category %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= params[:product] %></li>
  </ol>
</nav>
<% if @products.empty? %>
<div class="container">
  <p>No products found for <b><%= params[:product] %></b> in <%= @category %></p>
</div>
<% else %>  <div class = "container">
    <%= render partial: "products/products" %>
  </div>
<% end %>



app/views/products/_products.html.erb
<div class="container justify-content-center mt-50 mb-50">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 mt-2">
        <div class="card border-0">
          <div class="card-body">
            <div class="card-img-actions">
              <% if product.product_images[0].image.present? %>
                <%= image_tag product.product_images[0].image, :class => "card-img img-fluid", :width => 96, :height => 350, :alt => product.product_images[0] %>
              <% else %>
                <%= image_tag product.product_images[0].image_path, :class => "card-img img-fluid", :width => 96, :height => 350, :alt => product.product_images[0] %>
            <% end %>
            </div>
          </div>
          <div class="card-body bg-light text-center">
            <div class="mb-2">
              <h6 class="font-weight-semibold mb-2">
                <%= link_to product.product_name, product, :class => "text-default mb-2" %>
              </h6>
              <%= link_to product.category, product, :class => "text-muted" %>
            </div>
            <h3 class="mb-0 font-weight-semibold mb-2"><%= product.product_price %></h3>
            <!--          <div> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> </div>-->
            <!--          <div class="text-muted mb-3">34 reviews</div> -->
            <div class="px-2 mt-3">
<!--              <button class="btn btn-primary px-3">Buy Now</button>-->
            <% if @cart.include?(product) %>
              <%= button_to 'Remove From Cart', remove_from_cart_path(product.id), method: :delete, class: 'btn btn-outline-warning px-3' %>
            <% else %>
              <%= link_to 'Add To Cart', add_to_cart_path(product.id), method: :post, class: 'btn btn-outline-primary px-3'%>
            <% end %>
<!--              <button type="button" class="btn btn-outline-primary px-3"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>-->
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="pagination justify-content-center mt-3">
  <%= paginate @products, :class => "justify-content-center mt-3" %>
</div>

app/views/products/index.html.erb
<nav aria-label="breadcrumb no-bg">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">All Products</li>
  </ol>
</nav>
<%= render partial: "products" %>

app/views/products/show.html.erb
<nav aria-label="breadcrumb no-bg">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/categories">Categories</a></li>
    <li class="breadcrumb-item"><%= link_to @product.category, @product.category %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @product %></li>
  </ol>
</nav>

<div class="jumbotron">
  <div class="container">
    <div class="card" style="width: 18rem;">
      <%= image_tag @product.product_images[0].image_path, :class => "card-img-top", :alt => @product.product_name %>
      <div class="card-body">
        <h5 class="card-title"><%= @product.product_name %></h5>
        <p class="card-text"><%= @product.product_description %></p>
        <h3 class="mb-0 font-weight-semibold mb-2"><%= @product.product_price %></h3>
<!--        <a href="#" class="btn btn-primary">Buy Now</a>-->
        <% if @cart.include?(@product) %>
          <h6 class="text-muted"> Already in your cart</h6>
        <% else %>
          <%= link_to 'Add To Cart', add_to_cart_path(product.id), method: :post, class: 'btn btn-outline-primary px-3'%>
        <% end %>
      </div>
    </div>
  </div>
</div>